#include "core/core.cpp"
#include "platform/platform.h"
#include "renderer/renderer.h"
#include "profiler/profiler.h"
#include "game/game.cpp"
#include "renderer/renderer.cpp"
#include "platform/platform.cpp"
#include "profiler/profiler.cpp"